# Generated by Django 6.1 on 2026-08-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_remove_task_completed_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Выполнено')], default='new', max_length=20, verbose_name='статус'),
        ),
    ]
