# Generated by Django 6.1 on 2026-08-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_task_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted_batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='работает'),
        ),
        migrations.AddField(
            model_name='worker',
            name='deleted_batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='deleted_batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
