# Generated by Django 6.1 on 2026-08-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='number',
            field=models.PositiveIntegerField(verbose_name='номер'),
        ),
        migrations.AddConstraint(
            model_name='workshop',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('number',), name='unique_active_workshop_number'),
        ),
    ]
